mock_mode: true

data_fields:
  # Compliance fields from CharityAPI
  in_pub78:
    source: charityapi
    field: "deductibility"
  is_revoked:
    source: charityapi
    field: "status"
  has_recent_filing:
    source: charityapi
    field: "tax_period"

  # Organization type fields from CharityAPI
  ntee_code:
    source: charityapi
    field: "ntee_cd"
  subsection:
    source: charityapi
    field: "subsection"
  foundation_type:
    source: charityapi
    field: "foundation"
  filing_requirement:
    source: charityapi
    field: "filing_req_cd"
  ruling_year:
    source: charityapi
    field: "ruling"

  # Expense fields remain manual
  program_expenses:
    source: manual
    path: "fiscal_year_2024.expenses.program"
  admin_expenses:
    source: manual
    path: "fiscal_year_2024.expenses.admin"
  fundraising_expenses:
    source: manual
    path: "fiscal_year_2024.expenses.fundraising"

  # Charity Navigator remains manual
  charity_navigator_rating:
    source: manual
    path: "organization.charity_navigator_rating.stars"

  # ProPublica API fields
  total_revenue:
    source: api
  total_expenses:
    source: api

manual_data:
  directory: "manual"
  filename: "brief_manual.yaml"

propublica:
  base_url: "https://projects.propublica.org/nonprofits/api/v2"
  timeout: 30
  mock_mode: false

charityapi:
  base_url: "https://api.charityapi.org/api"
  api_key: "test_key"
  timeout: 30
  mock_mode: false

irs:
  local_data_dir: "cache"
  mock_mode: false

scoring:
  financial:
    program_expense_target: 0.75
    admin_expense_limit: 0.15
    fundraising_expense_limit: 0.15

preferences:
  mission_alignment:
    enabled: true
    priorities:
      A: medium   # Arts, Culture & Humanities
      B: high     # Education
      C: medium   # Environment
      D: low      # Animal-Related
      E: high     # Health
      F: high     # Mental Health & Crisis Intervention
      G: medium   # Voluntary Health Associations & Medical Disciplines
      H: high     # Medical Research
      I: low      # Crime & Legal-Related
      J: medium   # Employment
      K: medium   # Food, Agriculture & Nutrition
      L: medium   # Housing & Shelter
      M: medium   # Public Safety, Disaster Preparedness & Relief
      N: low      # Recreation & Sports
      O: high     # Youth Development
      P: high     # Human Services
      Q: medium   # International, Foreign Affairs & National Security
      R: medium   # Civil Rights, Social Action & Advocacy
      S: medium   # Community Improvement & Capacity Building
      T: low      # Philanthropy, Voluntarism & Grantmaking Foundations
      U: medium   # Science & Technology
      V: low      # Social Science
      W: medium   # Public & Societal Benefit
      X: low      # Religion-Related
      Y: low      # Mutual & Membership Benefit
      Z: low      # Unknown

  geographic_alignment:
    enabled: true
    preferred_states:
      - MA
      - DC
    acceptable_states:
      - NH
      - VT
      - RI
      - CT
      - NY

  organization_size:
    enabled: true
    small_max: 500000      # < $500k = Outstanding (grassroots)
    medium_max: 5000000    # $500k-$5M = Acceptable

caching:
  enabled: false
  database_path: "cache/test_cache.db"
  default_ttl_hours: 1
  propublica_ttl_hours: 1
  charityapi_ttl_hours: 1
  charity_navigator_ttl_hours: 1
  cleanup_on_startup: false